"""
First-run setup — interactive onboarding experience.
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.table import Table

from arc.identity.personality import list_personalities, get_personality
from arc.identity.soul import SoulManager


def run_first_time_setup(
    config_path: Path,
    identity_path: Path,
    console: Console | None = None,
) -> dict:
    """
    Run the first-time setup wizard.

    Returns dict with configuration values.
    """
    console = console or Console()

    # Banner
    console.print()
    console.print(
        Panel(
            "[bold cyan]"
            "   █████╗ ██████╗  ██████╗\n"
            "  ██╔══██╗██╔══██╗██╔════╝\n"
            "  ███████║██████╔╝██║     \n"
            "  ██╔══██║██╔══██╗██║     \n"
            "  ██║  ██║██║  ██║╚██████╗\n"
            "  ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝\n"
            "[/bold cyan]\n"
            "[dim]Welcome, human. Let's get acquainted.[/dim]",
            border_style="cyan",
        )
    )
    console.print()

    # Get user's name
    user_name = Prompt.ask(
        "[bold]What should I call you?[/bold]",
        default="User",
    )
    console.print()

    # Get agent's name
    agent_name = Prompt.ask(
        f"[bold]Nice to meet you, {user_name}! Now give me a name[/bold]",
        default="Arc",
    )
    console.print()

    # Show personality options
    console.print(f"[bold]Alright, I'm {agent_name}. What kind of AI am I?[/bold]")
    console.print()

    personalities = list_personalities()
    table = Table(show_header=False, box=None, padding=(0, 2))

    for i, p in enumerate(personalities, 1):
        table.add_row(
            f"[bold cyan]{i}[/bold cyan]",
            f"{p.emoji} [bold]{p.name}[/bold]",
        )
        table.add_row("", f"[dim]{p.description}[/dim]")
        table.add_row("", "")

    console.print(table)

    # Get personality choice
    choice = Prompt.ask(
        "[bold]Pick a number[/bold]",
        choices=[str(i) for i in range(1, len(personalities) + 1)],
        default="1",
    )
    personality = personalities[int(choice) - 1]
    console.print()
    console.print(f"[green]✓[/green] {personality.emoji} {personality.name} it is!")
    console.print()

    # Get Ollama URL
    console.print("[bold]Where's your Ollama server?[/bold]")
    ollama_url = Prompt.ask(
        "[dim]Base URL[/dim]",
        default="http://localhost:11434",
    )
    console.print()

    # Get model name
    ollama_model = Prompt.ask(
        "[bold]Which model should I use?[/bold]",
        default="llama3.1",
    )
    console.print()

    # Create identity file
    soul = SoulManager(identity_path)
    soul.create(agent_name, user_name, personality.id)

    # Create config file
    config_content = f'''# Arc Configuration
# Generated by arc init

[llm]
default_provider = "ollama"
default_model = "{ollama_model}"
base_url = "{ollama_url}"

[identity]
user_name = "{user_name}"
agent_name = "{agent_name}"
personality = "{personality.id}"

[security]
auto_allow = ["file:read"]
always_ask = ["file:write", "file:delete", "shell:exec"]
'''

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content, encoding="utf-8")

    # Success message
    console.print(
        Panel(
            f"[green]✓[/green] Identity saved to [cyan]{identity_path}[/cyan]\n"
            f"[green]✓[/green] Config saved to [cyan]{config_path}[/cyan]\n"
            "\n"
            "[bold]You're all set! Here's what you can do:[/bold]\n"
            "\n"
            "  [cyan]arc chat[/cyan]          — Talk to me\n"
            "  [cyan]arc run <recipe>[/cyan]  — Run a micro-agent\n"
            "  [cyan]arc teach <name>[/cyan]  — Teach me a new task\n"
            "\n"
            f"[dim]Try: [bold]arc chat[/bold][/dim]",
            title="[bold green]Setup Complete[/bold green]",
            border_style="green",
        )
    )

    return {
        "user_name": user_name,
        "agent_name": agent_name,
        "personality": personality.id,
        "ollama_url": ollama_url,
        "ollama_model": ollama_model,
    }